version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: redis

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:student
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: student_postgres_db

  celery:
    restart: always
    build: 
      context: .
    command: celery -A core worker -1 DEBUG
    volumes:
      - .:/code
    container_name: celery
    depends_on:
      - db
      - redis
      - web


volumes:
  postgres_data: